version: '3'

services:
  redis:
    image: redis
    container_name: db
    ports:
      - "6379:6379"

  chat:
    build: .
    ports:
      - "3000:3000"
    links:
      - redis
    environment:
      - REDIS_URL=redis://db